### PR TITLE
rename ko_image to ko_build

### PR DESCRIPTION
**Pull request by imjasonh**
Fixes https://github.com/ko-build/terraform-provider-ko/issues/52

This is pretty much just a mechanical search-and-replace, with the assumption that we don't care about maintaining any state if we expect users to just replace their resources with `ko_build`s and start from scratch. Let me know if you think this isn't the case and we need to do a state migration like we did for SBOMs.

### CODE REVIEW

**Review by joshrwolf — APPROVED** [review]
here is my meaningless 👍 !

**Comment by nsmith5** [comment]
For any existing usage when users do the same edit from `ko_image` -> `ko_build` the resulting terraform plan will try to delete `ko_image` and create `ko_build`, but this updated terraform provider doesn't know what `ko_image` is or how to delete it.  Perhaps smoother for users to leave `ko_image` in place, mark it deprecated by removing its create and read methods, but keeping a form or delete around (even if its still no-op) for the sake of a smooth transition

**Comment by mattmoor** [comment]
(just reading comments) we should keep `ko_image` and deprecate it.  I'd even be fine with leaving around the create/read for a while.  I feel like I have seen warnings from terraform before around deprecation (maybe from modules?) so if we could fine a way to do that I think it'd be ideal.

**Comment by nsmith5** [comment]
Yeah that is exactly what I was thinking. I think you also need to have a
no-op read to make it work, but you can verify in test

**Comment by imjasonh** [comment]
> Yeah that is exactly what I was thinking. I think you also need to have a no-op read to make it work, but you can verify in test


This PR now retains the `ko_image` resource with no-op create/read/deletes. I wasn't sure whether we needed to retain all the fields in `ko_image`, so I kept them. I figured the experience would be that any remaining `ko_image` resources in a config would be "valid" but then not do anything, vs having them show up as invalid / unknown field. WDYT?

**Review by mattmoor — APPROVED** [review]

**Pull request merged**
